<?php

/**
 * PDF template for default theme
 *
 * The default template only uses the custom_text placeholder as everything else will be auto-generated by the plugin.
 *
 * This template can be overridden by copying it to yourtheme/ezfc/pdf/default.php
 *
 */

if ( ! defined( "ABSPATH" ) ) {
	exit;
}

global $style;

?>
{{custom_text}}